shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<uuid:category_id>/', views.allProdCat, name='products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', views.prod_detail, name='prod_detail'),
]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null = True, blank = True)

shop/models.py
import uuid
from django.db import models
from django.urls import reverse

class Category(models.Model):
    id = models.UUIDField(
        primary_key = True,
        default = uuid.uuid4,
        editable = False)
    name = models.CharField(max_length = 250, unique = True)
    description = models.TextField(blank = True)
    image = models.ImageField(upload_to = 'category', blank = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args = [self.id])

    def __str__(self):
        return self.name
        
class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)

    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:prod_detail', args=[self.category.id, self.id])

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields +('age',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


def allProdCat(request, category_id=None):
    c_page = None
    products_list = None
    if category_id !=None:
        c_page = get_object_or_404(Category, id=category_id)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    return render(request, 'shop/category.html', {'category':c_page, 'products':products})


def prod_detail(request, category_id, product_id):
    try:
        product = Product.objects.get(category_id=category_id, id=product_id)
    except Exception as e:
        raise e
    return render(request, 'shop/product.html', {'product':product})

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous">
	<meta name="description" content="{% block metadescription %}{% endblock %}">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<div class = "container">
		{% include 'header.html' %}
		{% include 'navbar.html' %}
		{% block content %}
		{% endblock %}

		{% include 'footer.html' %}
	</div>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	  
</body>
</html>

shop/templates/footer.html
<div class = "footer navbar-fixed-bottom my-footer">
	<p class = "text-center">&copy; Online Cushions. All Rights Reserved.</p>
</div>

shop/templates/header.html
{% load static %}
<header>
    <div style="text-align: center;">
        <a href = "{% url 'shop:allProdCat' %}"><img src="{% static 'images/logo.png' %}" alt="Online Cushion Store"></a>
    </div>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Shop
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
                {% for cat in links %}
                <a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a>
                {% endfor %}
            </div>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class = "fas fa-shopping-cart"></i>Your Cart ({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0" action = "{% url 'search_app:searchResult' %}" method = "get">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>

shop/templates/shop/category.html
<html>
    <body>       
        {% extends "base.html" %}
        {% load static %}
        {% block metadescription %}
            {% if category %}
                {{ category.description|truncatewords:155 }}
            {% else %}
                Welcome to the cushion store where you can buy comfy and awesome cushions.
            {% endif %}
        {% endblock %}
        {% block title %}
            {% if category %}
                {{ category.name }} - Perfect Cushion Store
            {% else %}
                See Our Cushion Collection - Perfect Cushion Store
            {% endif %}
        {% endblock %}
        {% block content %}
        <!--Breadcrumb navigation-->
        {% if category %}
		<div class = "row my_row_class">
            <div class = "mx-auto">
                <p><a href = "{% url 'shop:allProdCat' %}">Our Product Collection</a></p>
            </div>
        </div>
        {% endif %}
        <div class = "mx-auto">
        {% if category %}
            <img class = "my_image" src="{{category.image.url}}" alt="{{category.name}}">
        </div>
        <br>
        <div>
            <h1 class = "text-center my_title">{{category.name}}</h1>
            <p class = "text-justify">{{category.description}}</p>
        </div>
        {% else %}
            <img class = "my_image my_image_padding" src="{% static 'images/banner.jpg' %}" alt="Our Products Collection">
        <br>
        <div>
            <h1 class = "text-center my_title">Our Products Collection</h1>
            <p class = "text-justify">Finding the perfect cushion for your room can instantly add to the levels of comfort and 
                sense of style throughout your home. They can transform the blandest of decors instantly 
                by adding colour, softness and an air of cosiness. As well as being comfy and looking great 
                our range of cushions will certainly embolden your décor with personalised charm.</p>
        </div>
        {% endif %}
    <div class = "container">
        <div class = "row mx-auto">
            {% for product in products.object_list %}
                <div class = "my_bottom_margin col-9 col-lg-4 col-sm-12 col-md-4">
                    <div class = "card text-center" style = "min-width:18rem;">
                        <a href="{{product.get_absolute_url}}"><img class = "card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                        <div class = "card-body">
                            <h4>{{product.name}}</h4>
                            <p>€{{product.price}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class = "mx-auto">
            {% if products.paginator.num_pages > 1 %}
                <hr>
                <div class = "text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href = "?page={{pg}}" class = "btn btn-light btn-sm
                            {% if products.number == pg %}active{% endif %}">{{pg}}
                        </a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}
    </body>
</html>

shop/templates/shop/product.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
	{{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
	{{ product.name }} - Perfect Cushion Store
{% endblock %}
{% block content %}
	<div class = "row my_prod_row_class">
		<div class = "mx-auto">
			<p><a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{product.category}}</a> | {{product.name}}</p>
		</div>
		<div class = "container">
			<br>
			<div class = "row">
				<div class = "col-12 col-sm-12 col-md-12 col-lg-6 text-center">
					<div style = "min-width: 18rem;">
						<img src="{{product.image.url}}" alt="{{product.name}}">
					</div>
				</div>
				<div class = "col-12 col-sm-12 col-md-12 col-lg-6 text-center">
					<div>
						<h1 class = "my_prod_title">{{product.name}}</h1>
						<p>£{{product.price}}</p>
						<p class = "my_title">Product Description</p>
						<p class = "text-justify my_prod_text">{{product.description}}</p>
						{% if product.stock == 0%}
							<p class = "text-justify my_prod_text"><b>Out of Stock</b></p>
						{% else %}
							<a class = "btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}